before:
  hooks:
    - go mod tidy

builds:
    - binary: simplehttpserver
      main: cmd/simplehttpserver/simplehttpserver.go
      goos:
        - linux
        - darwin
      goarch:
        - amd64
        - arm64

archives:
- format: binary

checksum:
  algorithm: sha256

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: 'New Release: {{ .ProjectName }} {{ .Tag }} is published! Check it out at {{ .ReleaseURL }}'

  discord:
    enabled: true
    message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'
